services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:latest
    container_name: data_importer_app
    ports:
      - "9003:80"
    volumes:
      - ./var/www/html/data-importer
    networks:
      - data-importer-network
    
  db:
    image: mysql:latest
    container_name: data_importer_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_importer
      # MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - data-importer-network

networks:
  data-importer-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  data_importer:
    driver: local
    driver_opts:
      type: none
      device: ./var/www/html/data-importer
      o: bind